/* Formatted on 11/21/2012 11:42:11 AM (QP5 v5.215.12089.38647) */
SELECT DISTINCT OPB_CM_DEPLOY.DEP_GROUP_NAME, OPB_SUBJECT.SUBJ_NAME
    FROM OPB_CM_DEPLOY_REF, OPB_CM_DEPLOY, OPB_SUBJECT
   WHERE     OPB_CM_DEPLOY_REF.DEP_GROUP_ID = OPB_CM_DEPLOY.DEP_GROUP_ID
         AND OPB_SUBJECT.SUBJ_ID = OPB_CM_DEPLOY_REF.SUBJECT_ID
         AND OPB_CM_DEPLOY.DEP_GROUP_NAME = 'IHUB_EM_MLR_TRIG_ENH_1'
ORDER BY OPB_SUBJECT.SUBJ_NAME DESC