 SELECT  
   DISTINCT  
   REP_DEPLOY_GROUP_DETAIL.dep_group_name as DG_NAME ,OBJECT_NAME,DEPLOY_TIME,TARG_SUBJECT_AREA
                            FROM   REP_DEPLOY_GROUP_DETAIL, REP_DEPLOY_GROUP
where  TARGET_REP_NAME = 'RS_PROD_CIGNA'AND
(
REP_DEPLOY_GROUP_DETAIL.TARG_SUBJECT_AREA like  '%BF_%' or 
REP_DEPLOY_GROUP_DETAIL.TARG_SUBJECT_AREA like  '%Billing-Finance%'
)                           AND TO_DATE (REP_DEPLOY_GROUP_DETAIL.DEPLOY_TIME,
                        'MM/DD/YYYY HH24:MI:SS') > (SYSDATE -173)
 