/* Formatted on 4/14/2012 10:56:55 PM (QP5 v5.126.903.23003) */

SELECT DISTINCT MAIN.MAPPING_NAME AS MAPPING_NAME,MAIN.INSTANCE_NAME AS
      INSTANCE_NAME,MAX(WID.ATTR_VALUE) AS CURRENT_VAL
      FROM (
      SELECT  DISTINCT MP.MAPPING_NAME,INST.INSTANCE_NAME,INST.WIDGET_ID ,MAX(
      INST.VERSION_NUMBER) AS VERSION
      FROM REP_WIDGET_INST INST JOIN REP_ALL_MAPPINGS MP ON MP.MAPPING_ID=INST
      .MAPPING_ID JOIN
      REP_SUBJECT SUB ON SUB.SUBJECT_ID=INST.SUBJECT_ID WHERE INST.WIDGET_TYPE_NAME=
      'Sequence'
      AND INST.SUBJECT_ID='116' GROUP BY MP.MAPPING_NAME,INST.INSTANCE_NAME,
      INST.WIDGET_ID ) MAIN JOIN OPB_WIDGET_ATTR WID ON WID.WIDGET_ID=MAIN.
      WIDGET_ID
      WHERE WID.WIDGET_TYPE='7'
      AND WID.ATTR_ID='4' GROUP BY MAIN.MAPPING_NAME ,MAIN.INSTANCE_NAME
      ORDER BY MAIN.MAPPING_NAME