SELECT distinct
-- REP_SUBJECT.SUBJECT_AREA ,
'pmrep  deletefolder  -n  '||REP_SUBJECT.SUBJECT_AREA AS pmrep1 
 FROM REP_SUBJECT WHERE 
 REP_SUBJECT.SUBJECT_AREA LIKE '%fdev3%'
 -- OR REP_SUBJECT.SUBJECT_AREA LIKE '%201104%'
 -- OR REP_SUBJECT.SUBJECT_AREA LIKE '%2009%'
 
