  SELECT distinct  REP_DEPLOY_GROUP_DETAIL.dep_group_name,REP_DEPLOY_GROUP.CREATION_TIME
              FROM   REP_DEPLOY_GROUP_DETAIL,REP_DEPLOY_GROUP
   WHERE   target_rep_name = 'RS_TST'
   and  REP_DEPLOY_GROUP_DETAIL.dep_group_name=REP_DEPLOY_GROUP.dep_group_name
   AND TO_DATE ( REP_DEPLOY_GROUP.CREATION_TIME,'MM/DD/YYYY HH24:MI:SS') < ADD_MONTHS (SYSDATE, - 6)
   ORDER BY   TO_CHAR (TO_DATE (REP_DEPLOY_GROUP.CREATION_TIME, 'MM/DD/YYYY HH24:MI:SS'),'MM/DD/YYYY') ASC;